workflow:
  name: Time Series Analysis Pipeline
  steps:
    - name: Fill Missing Values
      function: FillNA
      config:
        method: "ffill"
        field: "value"

    - name: Calculate Moving Average
      function: MovingAverage
      config:
        field: "value"
        window: 5

    - name: Linear Regression Prediction
      function: LinearRegressionPredictor
      config:
        predict_steps: 3

    - name: Rate of Change Alarm
      function: RateOfChangeAlarm
      config:
        field: "value_ma5"
        rate_threshold: 10.0

    - name: Trend Detection
      function: TrendDetector
      config:
        field: "value_ma5"
